### ISSUE TITLE
The initialization the `f_template` network

### ISSUE THREAD

**Issue by zhirui-gao** [jasonyzhang/ners#10]
Thanks for your awesome work. I noticed that"Once you have an object mesh and the corresponding sphere mesh, use the pre-processing script to initialize the `f_template` network" Why does it need to initialize the `f_template` network instead of using the original object mesh as the input?

**Comment by jasonyzhang** [comment]
Hi, f_template is initialized to have the same shape as the mesh. The shape model still needs to learn a mapping from sphere to your initial mesh shape.
