### ISSUE TITLE
Specifying cuboid extents

### ISSUE THREAD

**Issue by hniksoleimani** [jasonyzhang/ners#5]
I really appreciate the time and effort you put into this project, it would be great if someone would elaborate the how to specify cuboid extents in json file.

**Comment by jasonyzhang** [comment]
Hi,

When running the main script, you will specify a directory with images, masks, and associated metadata. The metadata file should contain 3 number for the cuboid extents, as shown here:

https://github.com/jasonyzhang/ners/blob/f9308e7b191b0a558a8566c366c883df17ba4170/data/espresso/metadata.json#L1
