### ISSUE TITLE
How to generate dataset  metadata.json

### ISSUE THREAD

**Issue by hzhshok** [jasonyzhang/ners#6]
Hello, 
    Thank you for giving an excellent nerf variant!
    Now i would like to make myself dataset for the wild using this, then could you please show me how to generate the data using which tool?  especially how to generate the metadata.json. 

Regards

**Comment by jasonyzhang** [comment]
Hi,

If you only have a few instances to annotate, I would suggest using the colab notebook to set azimuth, elevation, and extents visually.

If you have a large number of instances, you can set the extents manually and then use something like [PoseFromShape](https://github.com/YoungXIAO13/PoseFromShape) to automatically get camera poses
